#!/bin/env python3

from subprocess import check_output, CalledProcessError
from argparse import ArgumentParser
import difflib
from shutil import which
from os import path, mkdir
from datetime import datetime
import json


class Colors:
    """ ANSI color codes """
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    BLUE = "\033[0;34m"
    YELLOW = "\033[1;33m"
    GRAY = "\033[0;37m"
    BOLD = "\033[1m"
    END = "\033[0m"


if not which("pacman"):
    print("This program is designed for Arch linux and Arch-based users!! Other distro are not supported. You may simply duckduckgo \"how to check for package update in <your distro>\"")
    quit(3)


parser = ArgumentParser(
    description="Small program that prints packages avaliable")
parser.add_argument('--withAUR', action='store_true',
                    help='Enable AUR (requires to have aurutils installed)')
parser.add_argument('--show', '-s', action='store_true',
                    help='Show list of packages avaliable')
parser.add_argument('--omit', '-x', action='store_true',
                    help="Run without using cache file")
parser.add_argument('--force', '-f', action="store_true",
                    help="Force check for updates (same thing as -x except it writes to cache file)")

args = parser.parse_args()

CACHE_DIR = path.join(path.expanduser("~"), ".cache")


def get_update_from_call(aur: bool = False):
    if not which("checkupdates"):
        print(f"Install {Colors.BOLD}pacman-contrib{Colors.END} please")
        quit(1)
    try:
        print(f"{Colors.GRAY}Checking for updates...{Colors.END}")
        updates = check_output(["checkupdates"]).decode().splitlines()
        if aur:
            if not which("aur"):
                print(
                    f"Install {Colors.BOLD}aurutils{Colors.END} please. Better remove {Colors.BLUE}--withAUR{Colors.END} to ignore this!")
                quit(1)
            try:
                aur_updates = check_output(
                    "pacman -Qm | aur vercmp", shell=True).decode().splitlines()
                updates.extend(aur_updates)
            except CalledProcessError:
                pass
        return updates

    except CalledProcessError as e:
        if e.returncode == 2:
            print("No updates avaliable")
            quit(1)
        else:
            raise e


def get_avaliable_packages():
    if args.omit:
        return get_update_from_call(args.withAUR)
    if not path.isdir(CACHE_DIR):
        mkdir(CACHE_DIR)
    if not path.isfile(path.join(CACHE_DIR, "arch-checkupdate.json")):
        default_json = {
            "last-update": datetime.now().isoformat(),
            "withAUR": False,
            "packages": []
        }
        with open(path.join(CACHE_DIR, "arch-checkupdate.json"), 'x') as f:
            json.dump(default_json, f)
            f.close()
        return get_update_from_call(args.withAUR)
    with open(path.join(CACHE_DIR, "arch-checkupdate.json"), 'r+') as f:
        j = json.load(f)
        last_update = datetime.now().fromisoformat(j["last-update"])
        if datetime.now().day == last_update.day and len(j["packages"]) != 0 and (j["withAUR"] == args.withAUR or args.withAUR is False) and args.force is False:
            return j["packages"]
        else:
            packages_to_be_written = get_update_from_call(args.withAUR)
            j["packages"] = packages_to_be_written
            j["withAUR"] = args.withAUR
            j["last-update"] = datetime.now().isoformat()
            f.seek(0)
            json.dump(j, f)
            f.truncate()
            f.close()
            return packages_to_be_written


def get_color_diff(old_ver: str, new_ver: str):

    diff = difflib.ndiff(old_ver, new_ver)

    output_original = ""
    output_modified = ""

    for line in diff:
        code = line[:2]
        char = line[2:]
        if code == '  ':
            output_original += char
            output_modified += char
        elif code == '- ':
            output_original += Colors.RED + Colors.BOLD + char + Colors.END
        elif code == '+ ':
            output_modified += Colors.GREEN + Colors.BOLD + char + Colors.END

    return output_original, output_modified


def default_pacman_command() -> str:

    aur_helpers = ["yay", "paru", "pakku",
                   "pacaur", "aurman", "pikaur", "trizen"]
    for pkg in aur_helpers:
        if which(pkg):
            return pkg
    return "pacman"


def default_sudo() -> str:

    if not which("sudo"):
        return "doas"
    return "sudo"


if __name__ == "__main__":
    list = get_avaliable_packages()
    if args.show:

        lines = []

        for i in list:

            pkg_name, old_version, _, new_version = i.split(" ")
            color_old_version, color_new_version = get_color_diff(
                old_version, new_version)
            format_pkg_name = Colors.BOLD + pkg_name + Colors.END
            expand = " " * (30 - len(pkg_name))
            lines.append(
                len(f"{pkg_name}{expand}{old_version} -> {new_version}"))
            print(
                f"{format_pkg_name}{expand}{color_old_version} -> {color_new_version}")

        print("=" * max(lines))  # type: ignore

        print(
            f"{Colors.BLUE}{Colors.BOLD}{len(list)}{Colors.END} package{'s' if len(list) > 1 else ''} avaliable to update. Type {Colors.YELLOW}{default_sudo()} {default_pacman_command()} -Syu{Colors.END} to apply!")

    else:
        print(f"{Colors.BOLD}There are {Colors.BLUE}{len(list)}{Colors.END}{Colors.BOLD} package{'s' if len(list) > 1 else ''} avaliable!{Colors.END}\nType {Colors.GREEN}{Colors.BOLD}checkupdate --show{Colors.END} to show list of packages avaliable to update!")
